"""Initial Commit

Revision ID: 06d9d478c7fc
Revises: 
Create Date: 2024-04-15 23:28:32.046088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d9d478c7fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sec_Name', sa.String(length=128), nullable=True),
    sa.Column('Sec_Description', sa.Text(), nullable=True),
    sa.Column('Sec_Date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('Email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('Password', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['Email'])
        batch_op.drop_column('name')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('Password')
        batch_op.drop_column('Email')
        batch_op.drop_column('Name')

    op.drop_table('section')
    # ### end Alembic commands ###
