"""removed the unncessary parameters and added the necessary ones

Revision ID: 7c86b738d69b
Revises: 2f7db9f5496b
Create Date: 2024-04-18 01:11:23.337015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c86b738d69b'
down_revision = '2f7db9f5496b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_sec_name', ['Sec_Name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
