"""Initial Commit

Revision ID: c0f802c48f8a
Revises: 
Create Date: 2024-04-17 02:10:46.020752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f802c48f8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('Email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('Password', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('uq_email', ['Email'])  # Unique constraint on Email column
        batch_op.drop_column('email')
        batch_op.drop_column('password')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint('uq_email', type_='unique')  # Drop unique constraint on Email column
        batch_op.drop_column('Password')
        batch_op.drop_column('Email')
        batch_op.drop_column('Name')

    # ### end Alembic commands ###
